### ISSUE TITLE
Can this be launched in a web-app? Or built into a package hostable in a VM?

### ISSUE THREAD

**Issue by PirateBread** [aliostad/ConveyorBelt#12]
I only have access to an app-service-environment for running webapps/webjobs, or a VM. I cannot deploy to a cloud-service.

Thanks for your work this looks great.

**Comment by aliostad** [comment]
Hi, you should be able to run it using the ConsoleWorker. Have you not tried it?
https://github.com/aliostad/ConveyorBelt/tree/master/src/ConveyorBelt.ConsoleWorker
