### ISSUE TITLE
having eventhub as source

### ISSUE THREAD

**Issue by EmFl** [aliostad/ConveyorBelt#6]
Hello,
I'm wondering if it would it be possible to have an eventhub as source ? 
Since we can push azure audit log to an eventhub I could use conveyor belt to push in elasticsearch which would be really nice ...

**Comment by aliostad** [comment]
Hi, it is possible but unfortunately does not lend itself to the CB model which relies on a scheduler and publisher. My suggestion is to simply create a bridge that reads from EventHub and pushes to a table storage and then simply use the CB.
